import Navbar from '@/components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Cedric Jean-Philippe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark:bg-stone-900">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
